
#Modify the code below into HiveSQL

CREATE  TABLE IF NOT EXISTS `PRODUCT` (
  `PRODUCT_ID` INT NOT NULL ,
  `MANUFACTURER` INT NULL ,
  `DEPARTMENT` VARCHAR(45) NULL ,
  `BRAND` VARCHAR(12) NULL ,
  `COMMODITY_DESC` VARCHAR(45) NULL ,
  `SUB_COMMODITY_DESC` VARCHAR(45) NULL ,
  `CURR_SIZE_OF_PRODUCT` VARCHAR(12) NULL ,
  PRIMARY KEY (`PRODUCT_ID`) )
ENGINE = InnoDB;
